### ISSUE TITLE
Not showing custom model in STT node

### ISSUE THREAD

**Issue by SetaSouto** [watson-developer-cloud/node-red-node-watson#312]
I find a bug (I think) or at least an improvement that could be done to the node STT. I was using the node to listen to Spanish voices, so then I wanted to create a custom model, add a corpora and use the custom model. But when I came back to the node STT, it did not have the option to select the language customization. So, to find the customization, I was forced to restart the app and then it appears. It could be a good option to inspect or at least add that to the documentation of the node in node-red.

**Comment by chughts** [comment]
This will be because the node caches the list of available models in order to reduce traffic and the frequency of the calls to getModels. A refresh of the page will be sufficient to flush the cache. 

A coding change would need to detect that the cache is out of date, which only happens if a create custom model has succeeded, which can be as a result of an action outside of node-red. 

An alternative could be to have an option on the info panel to flush the cache. I favour this option.

Simplest would be an update the node information to mention that the cache can need refreshing.

**Comment by chughts** [comment]
Fixe in 0.5.12

**Comment by chughts** [comment]
Published.
