### ISSUE TITLE
Change to IAM powered URL for services needs update to bound service check.

### ISSUE THREAD

**Issue by prismboy** [watson-developer-cloud/node-red-node-watson#466]
Now SERVICE_IDENTIFER string are "text-to-speech" and "speech-to-text".
But CloudFoundry binding service names are "text_to_speech" and "speech_to_text".
So these nodes failed to get credentials.

**Comment by chughts** [comment]
This affects bound services when running in the cloud. Until rectified this will mean that new services will not be detected as connected. 

The panel asking for credentials and endpoints will be shown which when completed will allow the service to be found.

**Comment by chughts** [comment]
The nodes actually check for the service url, so the check for `text-to-speech` in the url is still valid. 

I am guessing that you are getting a invalid credentials error. This will be because all the services have switched off CF credentials and you will need to migrate your services and credentials to IAM.

**Comment by chughts** [comment]
What does appear to have changed is the structure of the URL endpoints 

from
`https://stream.watsonplatform.net/text-to-speech/api`

to
`https://api.us-south.text-to-speech.watson.cloud.ibm.com/instances/....`

This makes the current regex search fail to find the pattern. This affects all the nodes not just STT and TTS

**Comment by chughts** [comment]
Fixed in 0.8.0
