### ISSUE TITLE
Problem with watson assistant v2 - new session fix

### ISSUE THREAD

**Issue by tomkos** [watson-developer-cloud/node-red-node-watson#475]
Hi, after I've updated my app to the v0.9.2 version, I've notice that invalid sessions error are handled automatically, which is good. But there is another issue, after first reset of session. The session is being restarted every time new request is coming. 
Behavior:
- first request - no session id - new session is created S1 - correct
- second request -  S1 input param is send, same session is created - correct
- after 5 minutes - S1 input param is send, invalid session error (Resetting Session ... is visible in the view), - new session is created S2 - correct
- next request - S2 as input param, but STILL new session is created S3 - WRONG
- next request - S3 as input param,  but STILL new session is created S4 - etc..

Anyone had similar behavior?

**Comment by chughts** [comment]
Two of the changes made in 0.9.1 relate to this issue. 

The changes relate to two requirements:
1. For the node to manage renewal of expired sessions.
2. For the node to allow the use of identifiers for the session. This was due to flows integrating with nodes like twillio where the session id could not be remembered, but other ids like a telephone number could. 

So as of 0.9.1 if you send in a session id, it is used as an identifier. The node maps that to the real session id, which when it expires replaces it. 

When you provide a session id, and no mapped session exists for it, then a new 'real' session id is created. When a mapped session exits it is used. When you don't provide a session id, a new mapped session id is created. The naming is off, but pre 0.9.1 that is what was being input. 

So for your case, simply carry on providing S1, even when the node starts to emit S2.

I am keeping this issue open as:
1. The info panel needs to be more explicit on this usage
2. The node, could be amended to output the input session id. ie. always output S1, even when S1 is expired and all S1 is being used is as a look up for the live session id.

**Comment by tomkos** [comment]
I need to test it, as this is not that clear to me :D 
Basically this is very good, that node manage the session, so I will give it a try.

**Comment by tomkos** [comment]
We are strugglling a bit with this feature, as this is not backward compatible.... and now if we would like to upgrade to latest version, we would need to rework many integration points, is it possible to have some config property to turn it on or off?
Or node should return S1, even if some real session S2 was created...

**Comment by chughts** [comment]
I am happy to accept a pull request with this feature.

**Comment by tomkos** [comment]
Sure, pull request waiting for review and comments
